scalar JSON
scalar JSONObject

type Query {
  testing: String
}

type Mutation {
  testing: Boolean
}

type Subscription {
  testing: String
}

input PaginationInput {
  page: Int
  size: Int
}

type Pagination {
  total: Int
  size: Int
  current: Int
}
